AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  slack-pokerbot

  Sample SAM Template for slack-pokerbot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PokerBotConfigTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: pokerbot_config
      AttributeDefinitions: 
        - AttributeName: channel
          AttributeType: S
      KeySchema: 
        - AttributeName: channel
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  PokerBotSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: pokerbot_sessions
      AttributeDefinitions: 
        - AttributeName: channel
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema: 
        - AttributeName: channel
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  SlackPokerBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python2.7
      Events:
        SlackEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: POST
    Environment:
        Variables:
          SLACK_TOKEN: PUT YOUR TOKEN HERE
          IMAGE_LOCATION: PUT YOUR IMAGE LOCATION HERE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SlackPokerBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Slack Poker Bot"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  SlackPokerBotFunction:
    Description: "Slack Poker Bot Lambda Function ARN"
    Value: !GetAtt SlackPokerBotFunction.Arn
  SlackPokerBotFunctionIamRole:
    Description: "Implicit IAM Role created for Slack Poker Bot function"
    Value: !GetAtt SlackPokerBotFunctionRole.Arn
